### ISSUE TITLE
iOS SDK installation gives error

### ISSUE THREAD

**Issue by amacymind** [TuyaInc/tuyasmart_home_ios_sdk#59]
Hello,
I try to install tuya ios sdk using pods but every time pods gives me error for [!] Error installing TYBluetooth
I attach screenshot also.
![ss](https://user-images.githubusercontent.com/7520475/90420344-77283100-e0d5-11ea-8efd-cc291be38603.png)
Is there any problem fomr my side or server side?

Thanks,

**Comment by 0x5e** [comment]
Hi @amacymind  could you please provide some informations?
1. which country you located
2. ping airtake-public-data-1254153901.cos.ap-shanghai.myqcloud.com
3. ping images.tuyacn.com

if the problem still exists, please add following content in /etc/hosts as a temporary workaround:
```
58.217.230.27 airtake-public-data-1254153901.cos.ap-shanghai.myqcloud.com
```

Thanks

**Comment by amacymind** [comment]
1. I am from India
2. ping airtake-public-data-1254153901.cos.ap-shanghai.myqcloud.com gives me unknown host
3. ping images.tuyacn.com works

![Screenshot 2020-08-18 at 9 29 42 AM](https://user-images.githubusercontent.com/7520475/90469094-8dfe7000-e135-11ea-9ab7-4ebc1c015b98.png)

**Comment by 0x5e** [comment]
okay, we will use the second cdn url in the next versions, in current version please use that temporary workaround instead, thanks @amacymind

**Comment by amacymind** [comment]
Ok. temporary workaround works for now.

**Comment by aqibzigron** [comment]
hi i am getting same issue not able to install sdk since last two days 
[!] Error installing TYDeviceSyncModule
[!] /usr/bin/curl -f -L -o /var/folders/s3/pmgntkf54mn19lj1mp1_8h6c0000gn/T/d20230916-640-2libbu/file.zip https://airtake-public-data-1254153901.cos.ap-shanghai.myqcloud.com/smart/app/package/pods/ios/TYDeviceSyncModule-4.0.0-feature-420bizbundle.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 73 7266k   73 5322k    0     0  11189      0  0:11:05  0:08:07  0:02:58     0
curl: (56) Recv failure: Connection reset by peer
